### ISSUE TITLE
[Sampling] Sampling 익명화 결과의 k 값 사용

### ISSUE THREAD

**Issue by daehokimm** [jwkim-smu/kAnonimity#2]
* Sampling 단계
* kValue
  
Sampling 단계에서,  
샘플링된 데이터 중 다른 것과 동질집합을 이루지 못하는 데이터 1개가 있을 경우,  
해당 샘플링 데이터 셋을 익명화하면 kValue(최소 동질집합의 크기)는 **무조건 1**이 나옴.  
**그렇다면**  
해당 결과를 가지고 익명화를 하면 *무의미한 작업*이 됨.

**Comment by Kim-Taesu** [comment]
- Sampling 문제
  1. k를 주 관점이 아닌 사용자가 원하는 일반화 격자를 선택한다면 k값은 고려하지 않아도 된다.
      단점 : 하지만 k-익명화의 중심인 k값을 기준으로 익명화 하는것이 아님
  2. 최소 k값을 설정한다. 예를 들어 1~2의 k값인 경우 익명화를 하여도 동질 클래스의 개수가 적기 때문 
      에 보안성이 떨어짐
  3. 일단 일반화를 하고 K값으로 오름차순 정렬을하고 동질클래스를 선택, 선택해제 가능하게 한다.
      만약 동질클래스의 수가 1인 클래스가 있으면 선택 해제를 하여 그 클래스를 제외하고 K값을 구한다.

**Comment by daehokimm** [comment]
Sampling 단계를 Example 단계로 변경.
