### ISSUE TITLE
서버에서 Tomcat을 실행하고 외부에서 접속했을때 classpath 문제

### ISSUE THREAD

**Issue by Kim-Taesu** [jwkim-smu/kAnonimity#3]
서버 이클립스 환경에서 실행하면 문제 없이 실행되지만

외부 접속후 jsp를 이용해서 package를 import를 하면 경로를 찾지 못함 

========================ERROR LOG==================================

HTTP Status 500 – Internal Server Error
Type Exception Report

Message /loginAction.jsp (line: [10], column: [0]) The value for the useBean class attribute [user.User] is invalid.

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.apache.jasper.JasperException: /loginAction.jsp (line: [10], column: [0]) The value for the useBean class attribute [user.User] is invalid.
	org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
	org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:291)
	org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:114)
	org.apache.jasper.compiler.Generator$GenerateVisitor.visit(Generator.java:1379)
	org.apache.jasper.compiler.Node$UseBean.accept(Node.java:1187)
	org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2392)
	org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2444)
	org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2450)
	org.apache.jasper.compiler.Node$Root.accept(Node.java:471)
	org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2392)
	org.apache.jasper.compiler.Generator.generate(Generator.java:3664)
	org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:254)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:374)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:351)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:335)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:595)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:368)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Note The full stack trace of the root cause is available in the server logs.

**Comment by daehokimm** [comment]
?? 정확히 어떤 상황인지 자세한 설명 부탁쓰~
이클립스 환경에서 실행하는 것과 외부 접속이라는 상황이 어떤 차이인지 구분하기 어려움!

**Comment by Kim-Taesu** [comment]
서버 원격 접속후 이클립스 환경에서 프로젝트 파일 import하고 index.jsp를 톰캣 서버로 실행 시키면 jsp useBean 클래스 이용시 src폴더에 있는 패키지들이 정상적으로 읽혀집니다

그런데 외부 접속을 가능하게 하기 위해 이클립스 환경이 아닌 터미널 버전에서 tomcat서버를 실행시키고 서버 ip(117.16.123.55)에 접속하면 index.jsp와 나머지 화면까지는 잘 출력이 되지만 src폴더의 패키지들을 불러올때 classpath오류가 생겨서 문제가 생깁니다!

**Comment by daehokimm** [comment]
이클립스에서 실행해보고 외부 접속은 안되는거야?

**Comment by Kim-Taesu** [comment]
넵! 이거 첨해봐서 제가 못하는거일수도 있는데 일단 이클립스에서 실행했을때 접속은 안됐어요!

**Comment by Kim-Taesu** [comment]
톰캣 classpath, 설정 파일 재 setup 후 오류 해결
